### ISSUE TITLE
cannot compile with Intel icpc 16.0.3 (C++11 flag problem?)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#396]
(no problem with Intel icpc 18)

In file included from /poubelle/coulais/icc/gdl/src/FMTOut.cpp(5):
/poubelle/coulais/icc/gdl/src/FMTOut.hpp(33): error: namespace "std" has no member "unique_ptr"
  std::unique_ptr<std::ostream> osLocalGuard;
       ^
In file included from /poubelle/coulais/icc/gdl/src/FMTOut.cpp(5):
/poubelle/coulais/icc/gdl/src/FMTOut.hpp(33): error: type name is not allowed
  std::unique_ptr<std::ostream> osLocalGuard;
                  ^
In file included from /poubelle/coulais/icc/gdl/src/FMTOut.cpp(5):
/poubelle/coulais/icc/gdl/src/FMTOut.hpp(33): error: identifier "osLocalGuard" is undefined
  std::unique_ptr<std::ostream> osLocalGuard;
                                ^
compilation aborted for /poubelle/coulais/icc/gdl/src/FMTOut.cpp (code 2)

**Comment by slayoo** [comment]
c++11
did Cmake issue any warning?
