### ISSUE TITLE
Develop tests involving pointers, objects - in IDL

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#165]
We need more test routines that stress the GDL internals for robustness.
As of version 0.9.8 we can expect GDL to be an easy mark for segfaults, etc. when 
a lot of pointer and object manipulation occurs.  Positive results should be obtained in
 IDL for stress-testing that GDL will later be able to survive. 

 As an example I include "maketree" which uses pointers, lists, and IDL_CONTAINER. 
[maketree.zip](https://github.com/gnudatalanguage/gdl/files/1905829/maketree.zip)

  I don't think this will run well (yet) in git GDL, but it should be ok in IDL.
Here it is running on my GDL code:
`GDL> .run maketree
% Compiled module: NEW_DIRSET.
% Compiled module: NEXTLEVEL.
% Compiled module: NEWLEVEL.
% Compiled module: FLATTEN.
% Compiled module: MAKETREE.
% Compiled module: TREENODE__DEFINE.
GDL> mt = maketree()
GDL> help,/heap
Heap Variables:
    # Pointer: 1562
    # Object : 42
GDL> help,mt
MT              STRUCT    = -> TREENODE Array[1]
** Structure TREENODE, 3 tags,memsize =40, data length=35/35:
   DIRNAME         STRING    'D:/home/greg/gdlpro'
   FILES           LIST      <ID=5  N_ELEMENTS=0>
   SUBDIRS         LIST      <ID=6  N_ELEMENTS=7>
GDL> delvar,mt
GDL> help,/heap
Heap Variables:
    # Pointer: 0
    # Object : 0

GDL>`

**Comment by maynardGK** [comment]
Congratulations! #523  is the first example satisfying this. 
-  Save/restore doesn't  work for pointers,
- inherits: idl_object} is needed to be explicitly part of the low-level :
    (probably an implicit inheritance in IDL)
 ```
pro obj1__define
  struct = {obj1, ptr:ptr_new(), var:0, inherits: idl_object}
  return
% Compiled module: PATH_SEP.
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > this-
() (which is 0)
GDL> jj=obj_new('idl_object')
GDL> help,jj,/full
JJ              OBJREF    = <ObjHeapVar1(GDL_OBJECT)>
** Structure GDL_OBJECT, 3 tags,memsize =24, data length=24/24:
   GDL_OBJ_TOP     LONG64                         0
   __OBJ__         OBJREF    <NullObject>
   GDL_OBJ_BOTTOM  LONG64                         0
Method procedures (1):
 _OVERLOADBRACKETSLEFTSIDE
Method functions (7):
 INIT _OVERLOADBRACKETSRIGHTSIDE _OVERLOADEQ _OVERLOADISTRUE _OVERLOADMINUS _OVERLOADNE _OVERLO
GDL> my_obj = obj_new('obj1')
% Compiled module: OBJ1__DEFINE.
% OBJ1__DEFINE: Variable is undefined: IDL_OBJECT
% Execution halted at: OBJ1__DEFINE        39 D:\home\greg\testing\test_save\obj1__define.pro
%                      $MAIN$
GDL> my_obj = obj_new('obj1')
GDL> help,/full,my_obj
MY_OBJ          OBJREF    = <ObjHeapVar2(OBJ1)>
** Structure OBJ1, 2 tags,memsize =10, data length=10/10:
   PTR             POINTER   <PtrHeapVar1>
   VAR             INT             13
Method procedures (1):
 CLEANUP
Method functions (3):
 GET_PTR GET_VAR INIT
```
even after idl_object has been defined, the routine does not recognize it on the first try.  IDL_OBJECT is a name that should be internally recognized, and equivalent to, 'GDL_OBJECT' which is hardwired to be
an object present at GDL invocation.    Every object should already inherit a GDL_OBJECT without having to call it out, if it isn't inheriting some other object.
```
pro obj1__define
  struct = {obj1, ptr:ptr_new(), var:0, inherits: gdl_object}
                                                       ^^^^^^^^^^^^^ 
         this will make an object work but should not be necessary.
  return
```

**Comment by astromark** [comment]
Hi, I've just been trying some of my code to see if it works with version 1.0.0-rc.3 and I think I've come across this problem.

I have a nested pointer, ptr1:
```
GDL> help, *ptr1
** Structure <Anonymous>, 5 tags,memsize =240, data length=153/234:
   READINFO        STRUCT    -> <Anonymous> Array[1]
   READWIDS        INT       Array[1]
   PTR_READOP      POINTER   <PtrHeapVar2>
   VIEWINFO        STRUCT    -> <Anonymous> Array[1]
   PTR_INTOP       POINTER   <PtrHeapVar3>

```
I then set ptr2 equal to one of the nested pointers.
```
GDL> ptr2 = (*ptr1).ptr_readop
GDL> help, *ptr2
** Structure <Anonymous>, 30 tags,memsize =1161040, data length=1161030/1161030:
   CS              FLOAT     Array[8, 180, 201]
   NR              FLOAT           202.000
   NT              FLOAT           181.000
   NP              FLOAT           9.00000
   NRLESS2         FLOAT           200.000
   NTLESS2         FLOAT           179.000
   NPLESS2         FLOAT           7.00000
   RSTEP           FLOAT          0.149254
   TSTEP           FLOAT         0.0349066
   PSTEP           FLOAT         0.0327249
   RCENTRE         FLOAT     Array[201]
   TCENTRE         FLOAT     Array[180]
   PCENTRE         FLOAT     Array[8]
   RCMIN           FLOAT           54.9254
   TCMIN           FLOAT        -0.0174620
   PCMIN           FLOAT         -0.147262
   RCCSMIN         FLOAT           54.9254
   TCCSMIN         FLOAT        -0.0174603
   PCCSMIN         FLOAT         -0.114536
   RCCSMAX         FLOAT           85.0746
   TCCSMAX         FLOAT           6.30064
   PCCSMAX         FLOAT          0.147261
   TCONT           BYTE         1
   PCONT           BYTE         0
   RB              FLOAT     Array[203]
   RBMIN           FLOAT           54.7761
   RBSTEP          FLOAT          0.149254
   NRBMAX          LONG               202
   BFLUX           FLOAT     Array[1, 203]
   WVBAND          FLOAT     Array[1]

```
But when I try and access data in it, I get a segfault.
```
GDL> conv = (*ptr2).wvband(0)^2/2.99792458
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Aborted (core dumped)

```

**Comment by GillesDuvert** [comment]
Interesting, although not unexpected :smile:  (pointer to pointer to structure element...)
Would you be kind enough to prepare a small test procedure to reroduce the bug? Thank in advance.

**Comment by astromark** [comment]
I was afraid you were going to ask that. It's part of the last procedure in a series of long procedures, so it'll take a bit of work to reduce it down to a small test procedure. I'll see what I can do.

**Comment by astromark** [comment]
Actually, it was easier than I expected. The following is enough to make it crash.

```
allinfo             = {ptr_readop:ptr_new(/allocate_heap)}
ptr1                = ptr_new(allinfo)

readop = {bflux:[2e-3,1.5e-3],wvband:[850.,1300.]}
*(*ptr1).ptr_readop = readop

ptr2 = (*ptr1).ptr_readop
conv = (*ptr2).wvband(0)^2/2.99792458

```

**Comment by maynardGK** [comment]
wvband(0) invokes the crash (tries to find a function).  WFM when I use wvband[0].

  failure comes after de-referencing the pointer - double indirect is not needed.
````
GDL> readop = {bflux:[2e-3,1.5e-3],wvband:[850.,1300.]}
GDL> wvb=readop.wvband(0)  ;  Works ok like this
GDL> p=ptr_new(readop)
GDL> t=(*p).wvband(0)
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
````

**Comment by GillesDuvert** [comment]
yes it is not a pointer problem but a GDL interpreter (antlr code). At least should not crash, minimally like that:
```
GDL> conv = (*ptr2).wvband(0)
Interpreter exception: unexpected AST node: deref
```

**Comment by maynardGK** [comment]
> * inherits: idl_object} is needed to be explicitly part of the low-level :
>   (probably an implicit inheritance in IDL)
> 
> ```
> pro obj1__define
>  struct = {obj1, ptr:ptr_new(), var:0, inherits: idl_object}
>  return
> % Compiled module: PATH_SEP.
> D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > this-
> () (which is 0)
> GDL> jj=obj_new('idl_object')
> GDL> help,jj,/full
> ...
> GDL> my_obj = obj_new('obj1')
> % Compiled module: OBJ1__DEFINE.
> % OBJ1__DEFINE: Variable is undefined: IDL_OBJECT
> % Execution halted at: OBJ1__DEFINE        39 D:\home\greg\testing\test_save\obj1__define.pro
> %                      $MAIN$
> ...
> 
> even after idl_object has been defined, the routine does not recognize it on the first try. IDL_OBJECT is a name that should be internally recognized, and equivalent to, 'GDL_OBJECT' which is hardwired to be
> an object present at GDL invocation. Every object should already inherit a GDL_OBJECT without having to call it out, if it isn't inheriting some other object.
> 
> ```
> pro obj1__define
>   struct = {obj1, ptr:ptr_new(), var:0, inherits: gdl_object}
>                                                        ^^^^^^^^^^^^^ 
>          this will make an object work but should not be necessary.
>   return
> ```

UPDATE:  Since, Some of the antlr code was refined and overload.cpp also modified so that the current result looks ok:
GDL> jj=obj_new('idl_object')
GDL>  help,jj,/full
JJ              OBJREF    = <ObjHeapVar1(GDL_OBJECT)>
** Structure GDL_OBJECT, 3 tags,memsize =24, data length=24/24:
   IDL_OBJECT_TOP  LONG64                         0
   __OBJ__         OBJREF    <NullObject>
   IDL_OBJECT_BOTTOM
                   LONG64                         0
GDL> help,jj,/full,/obj
** Object class GDL_OBJECT, 0 direct superclasses, 8 known methods
   Known Function Methods:
      GDL_OBJECT::_OVERLOADISTRUE
      GDL_OBJECT::INIT
      GDL_OBJECT::_OVERLOADBRACKETSRIGHTSIDE
      GDL_OBJECT::_OVERLOADEQ
      GDL_OBJECT::_OVERLOADNE
      GDL_OBJECT::_OVERLOADPLUS
      GDL_OBJECT::_OVERLOADMINUS
   Known Procedure Methods:
      GDL_OBJECT::_OVERLOADBRACKETSLEFTSIDE
** Structure GDL_OBJECT, 3 tags,memsize =24, data length=24/24:
   IDL_OBJECT_TOP  LONG64                         0
   __OBJ__         OBJREF    <NullObject>
   IDL_OBJECT_BOTTOM
                   LONG64                         0
GDL> my_obj = obj_new('obj1')
% Compiled module: OBJ1__DEFINE.
GDL> help,/full,my_obj,/obj
** Object class OBJ1, 0 direct superclasses, 4 known methods
   Known Function Methods:
      OBJ1::INIT
      OBJ1::GET_PTR
      OBJ1::GET_VAR
   Known Procedure Methods:
      OBJ1::CLEANUP
** Structure OBJ1, 2 tags,memsize =10, data length=10/10:
   PTR             POINTER   <NullPointer>
   VAR             INT              0
GDL> help,/sour
Compiled Procedures:
$MAIN$
OBJ1__DEFINE             D:/home/greg/gdlpro/objects/obj1__define.pro

Compiled Functions:
GDL> $cat D:/home/greg/gdlpro/objects/obj1__define.pro
;+
; test object for save/restore
;-

function obj1::init

  self.ptr    = ptr_new(/allocate)
  *(self.ptr) = 42

  self.var = 13

  ; Initialization succesful
  return, 1

end

pro obj1::cleanup
;+
; Mandatory cleanup procedure
;-

  ptr_free, self.ptr

end

function obj1::get_ptr
  return, self.ptr
end

function obj1::get_var
  return, self.var
end

pro obj1__define
;+
; Object definition
;-

  struct = {obj1, ptr:ptr_new(), var:0}

  return

end

**Comment by GillesDuvert** [comment]
thanks @maynardGK !
Leaving open as not solved and contains a nice testcase.

**Comment by GillesDuvert** [comment]
please test anew, and submit simple test cases in case of issues.
