### ISSUE TITLE
test_hdf5 fails on the installed package

### ISSUE THREAD

**Issue by olebole** [gnudatalanguage/gdl#537]
`test_hdf5` passes during the Debian package build, but fails in the CI test with the installed package:
```
% Compiled module: TEST_HDF5.
% Compiled module: FILE_SEARCH_FOR_TESTSUITE.
% Compiled module: PATH_SEP.
% H5D_OPEN: Invalid arguments to routine
% Execution halted at: TEST_HDF5_BYTE_ARRAY    25 /tmp/autopkgtest-lxc.0qji9dvf/downtmp/build.BKC/src/testsuite/test_hdf5.pro
%                      TEST_HDF5          109 /tmp/autopkgtest-lxc.0qji9dvf/downtmp/build.BKC/src/testsuite/test_hdf5.pro
%                      $MAIN$          
```

Full test log [here](https://ci.debian.net/data/autopkgtest/unstable/amd64/g/gnudatalanguage/1424164/log.gz), the build log is [here](https://buildd.debian.org/status/fetch.php?pkg=gnudatalanguage&arch=amd64&ver=0.9.9-1&stamp=1543698771&raw=0).

**Comment by olebole** [comment]
Manually, I can confirm the failure:
```IDL
GDL> file_id = H5F_OPEN('byte_array.h5')
GDL> data_id = H5D_OPEN(file_id, 'g1/d1')
% H5D_OPEN: Invalid arguments to routine
% Execution halted at: $MAIN$          
```
hdf5 is properly installed, since the `H5F_OPEN` function works well.  With h5py, I can properly open the file and the dataset `g1/d1`. I have no idea why this test succeeds during the build.

**Comment by alaingdl** [comment]
Hi Ole

I can confirm the problem on a Debian machine with  libhdf5-dev         1.10.0-patch1+

It is working nicely on my laptop (U14.04) with libhdf5-dev         1.8.11-5ubuntu

**Comment by alaingdl** [comment]
and yes, this test is OK on both machines, with IDL 8.4 & 8.7

**Comment by pini-gh** [comment]
Please note that in HDF5 1.10.x, the hid_t type is now uint64 instead of int in HDF5 1.8.x.

**Comment by alaingdl** [comment]
thanks so much, that may explain this regression !

**Comment by pini-gh** [comment]
Then in the hdf5_fun module many DLong should be changed in DLong64 depending on the HDF5 release.

**Comment by alaingdl** [comment]
stupid question : how to know which ones should be changed ??

I just changed *all* DLong & DLongGDL into  DLong64 & DLong64GDL
and now the test is OK on my Debian where I had trouble before ...

**Comment by pini-gh** [comment]
There is no choice but to check each H5 function signature in hdf5_fun.cpp.

**Comment by alaingdl** [comment]
[The hid_t type was changed from 32-bit to a 64-bit value.](https://portal.hdfgroup.org/display/support/HDF5+1.10.0)

**Comment by alaingdl** [comment]
Looking in the IDL documentation, and testing on IDL 8.7.0, they are still in hdf5 1.8
```
IDL> !version.release
8.7.0
IDL> H5_GET_LIBVERSION( )
1.8.11
```

as a result, in some place, they still use "old" Long value, not Long64

**Comment by olebole** [comment]
Jut curious: Is there a reason, why `hdf5_fun.cpp` doesn't use `hid_t`, but `DLong`?

**Comment by alaingdl** [comment]
thanks ! I tried that this afternoon but received huge fatals :)

```
[ 15%] Building CXX object src/CMakeFiles/gdl.dir/hdf5_fun.cpp.o
/home/coulais/GDL/gdl-0.9.8git181129CMake/src/hdf5_fun.cpp: In function ‘BaseGDL* lib::h5g_open_fun(EnvT*)’:
/home/coulais/GDL/gdl-0.9.8git181129CMake/src/hdf5_fun.cpp:302:37: error: no matching function for call to ‘AssureLongScalarPar(int, hid_t&)’
     e->AssureLongScalarPar(0, h5f_id);
                                     ^
In file included from /home/coulais/GDL/gdl-0.9.8git181129CMake/src/hdf5_fun.hpp:21:0,
                 from /home/coulais/GDL/gdl-0.9.8git181129CMake/src/hdf5_fun.cpp:32:
/home/coulais/GDL/gdl-0.9.8git181129CMake/src/envt.hpp:844:8: note: candidate: void EnvT::AssureLongScalarPar(SizeT, DLong&) <near match>
   void AssureLongScalarPar( SizeT ix, DLong& scalar);
        ^~~~~~~~~~~~~~~~~~~

```


typicalemnt messages which are not clear for me

**Comment by pini-gh** [comment]
You may have to cast it to (DLong64&) :
`e->AssureLongScalarPar(0, (DLong64&) h5f_id);`

**Comment by alaingdl** [comment]
Ok, I made progress. The situation is much more complex that initially expected.
But I succeed to have code working with hdf5 1.8 & 1.10
We have to expect serious issue when/if IDL will change hdf5 version !

the line
```
#define H5_USE_16_API 1
```
in *hdf5_fun.hpp* is also a problem.

If I put in Git what I did, I suspect the hdf5 support for versions below 1.8 will be broken. (due to various changes in interface)

**Comment by olebole** [comment]
@alaingdl Could you open a pull request for that? That would help to see what exactly was changed. And I could cherrypick it to fix the Debian package from there.
Is support for hdf5 before 1.8 needed?

**Comment by olebole** [comment]
@alaingdl Do you have something (a patch, or a branch) that I could use to fix this issue on the 0.9.9 release? The GDL is currently not in Debian testing due to this failure. I could also now either ignore this failire, or (temporarily) remove hdf5 support in the package. Any hints?

**Comment by alaingdl** [comment]
not sure to have time this week end, should be OK just after Xmax

**Comment by alaingdl** [comment]
As it has been triggered by the discussion, the problem arises because of serious change in HDF5 between 1.8  and 1.10. Outside GDL. And the change in HDF *for me* breaks what I expect as basic compatibility  between versions. Since 1.10, most functions have two interface, _1_ and _2_ but an unclear side effect is the  *hid_t* is become a long64 instead of a long ([clear](https://github.com/HDFGroup/HDF.PInvoke/wiki/Important-Differences-between-HDF5-1.8-and-1.10), [less clear](https://www.hdfgroup.org/2018/04/why-should-i-care-about-the-hdf5-1-10-2-release/) : do those new flags may help ? ) and I did not succeed to solve that.

Then, interface _1_ in 1.10 don't give same index  that same function in 1.8 ! Why having a _1_ in that case ?

Even the last versions (8.7x) of IDL is still using HDF5 1.8 indexes (long and not long64) 

I derived a very basic c++ code (see below : test_hdf5_open.cpp) to mimic our problem, and give here the result.

old lib : hdf5 1.8.11-5ubuntu7.1 

```
$ h5c++ test_hdf5_open.cpp
$ ./a.out 
16777216
83886080
```

new lib : hdf5 1.10.0-patch1+docs-3+d (debian)

```
$ h5c++ test_hdf5_open.cpp
$ ./a.out 
72057594037927936
360287970189639680
```

Lest be clear, the way I used and set flags and compiled should ensure the _old_ behavior (using the old _1_ template, not the new _2_). See from my end users point of view, I would have expect that the outputs would have been the same (same interfaces, different values .. hum hum)

If I comment out the line _ #define H5_USE_16_API 1_ the compilation failed in 1.10 because it will try to use the new _2_ interface 
```
error: too few arguments to function ‘hid_t H5Dopen2(hid_t, const char*, hid_t)’
```

And yes I try to force  *hid_t* to be a _long_ in 1.10, without success

Sorry for this long message, I try to explain the situation  (for me, code compiled with 1.10 and 
__ #define H5_USE_16_API 1_ __  should behave as 1.8 but don't)

Comments and helps very welcome.

Alain

Ps: test_hdf5_open.cpp

```
#include <string>
#include <iostream>

#define H5_USE_16_API 1
#include <H5version.h>
#include "hdf5.h"

using namespace std;

int main()
{
 // file already available in testsuite ...
  string h5fFilename="byte_array.h5";
  string h5dDatasetname="g1/d1";

  hid_t h5f_id, h5d_id;

  h5f_id = H5Fopen(h5fFilename.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
  cout << (long)h5f_id << endl;
    
  h5d_id = H5Dopen(h5f_id, h5dDatasetname.c_str());
  cout << (long)h5d_id << endl;

}
```

**Comment by pini-gh** [comment]
The H5_USE_16_API flag doesn't act on the hid_t size. A standard C or C++ HDF5 program using correctly the hid_t type shouldn't care about its size. This is a problem though for software like GDL where this size matters. There is no choice but to fix GDL to acknowledge this new hid_t size.

**Comment by alaingdl** [comment]
ok, I just pushed an attempt, working here for _hdf5 1.8.11-5ubuntu7.1_ and _hdf5 1.10.0-patch1+docs-3+d (debian)_

I carefully checked all functions (if they need a cleanup)

the tests cover only very limited number of functions, extensions welcome

**Comment by alaingdl** [comment]
I delivered the PR #560 few hours ago, with lot of tests before. I learnt a lot !

**Comment by alaingdl** [comment]
Change tested with success on various targets (Linux + OSX) without issue.

More test cases very welcome. Better coverage of HDF5 capabilities would be great as this format is gaining interest ... Users also have to make request or contributions. Can be a good topic for short intership (implementation + tests)
